### ISSUE TITLE
TypeError Intesis Daikin DK-RC

### ISSUE THREAD

**Issue by modi80** [jhschuster/homebridge-intesisweb#7]
Hi,
it would be great if you could make Intesis Daikin Controlker DK-RC also work with your plugin. Currently I am only getting a TypeError. Thank you for your help!
Tim

**Comment by jhschuster** [comment]
Which specific kind of controller do you have? The website lists several DK-RC subtypes (https://www.intesis.com/products/ac-interfaces/daikin-gateways)

Intesis sure has increased the number of options since the last time I looked a few years ago. This plugin should work with any of their devices that goes to "AC Cloud Control", like the "Universal IR Air Conditioner to AC Cloud Control [WiFi] Interface" (which is what I have and what the plugin was written for) or the "Daikin AC Domestic units to AC Cloud Control [WiFi] Interface" (I'm guessing).

The plugin works by scraping the AC Cloud Control website, pretending it's you doing various things on the website. I have Fujitsu AC units. I'm assuming the UI of AC Cloud Control (https://accloud.intesis.com/) is the same regardless of the kind of units you have installed.

**Comment by jhschuster** [comment]
I really have no idea why the homebridge-intesisweb plugin interferes with homebridge-homematicip one. If you disable the homematicip plugin, does the Intesis one work for you? Literally all the plugin does is emulate a person logging in to AC Cloud Control, scraping values from the returned web pages to update status and, when HomeKit tries change something, pretending a person did the actions on the AC Cloud Control website.

**Comment by modi80** [comment]
Hey, I [now noticed](https://github.com/marcsowen/homebridge-homematicip/issues/66#issuecomment-841047763) that I only needed to complete restart Hoobs after configuring your Plugin (the automatic service restart was not enough). And now it's working together!

**Comment by jhschuster** [comment]
I'm glad you figured it out!
